In [1]:
import pandas as pd

In [2]:
info = {
    "name" : ["MIT","KAVY","DEV","KISHAN"],
    "cgpa" : [9.9 , 9.6 , 8.9 , 8.8]
}

In [3]:
df = pd.DataFrame(info)

print(df)

     name  cgpa
0     MIT   9.9
1    KAVY   9.6
2     DEV   8.9
3  KISHAN   8.8

In [4]:
df

     name  cgpa
0     MIT   9.9
1    KAVY   9.6
2     DEV   8.9
3  KISHAN   8.8

In [12]:
stu_info = {
    "name" : ["MIT","KAVY","DEV","KISHAN"],
    "cgpa" : [9.9 , 9.6 , 8.9 , 8.8],
    "age" : [21,21,21,21]
}

stu_df = pd.DataFrame(stu_info)

stu_df

     name  cgpa  age
0     MIT   9.9   21
1    KAVY   9.6   21
2     DEV   8.9   21
3  KISHAN   8.8   21

In [11]:
print(type(stu_df))
print(df.index)
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'cgpa'], dtype='object')

# Make DATA FRAME FROM LIST OF LIST

In [14]:
list_df = pd.DataFrame([["MIT","KISHAN"] , [21 , 23]] , columns = ["NAME" , "AGE"])

list_df

  NAME     AGE
0  MIT  KISHAN
1   21      23

# Make DATA FRAME FROM NUMPY ARRAY

In [16]:
import numpy as np

arr = np.array([["MIT","KISHAN"] , [21 , 23]])

numpyarr_df = pd.DataFrame(arr , columns = ["NAME" , "AGE"])

numpyarr_df

  NAME     AGE
0  MIT  KISHAN
1   21      23