In [2]:
import pandas as pd

# Transforming Data ( Feature Engineering )

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pandas/employee_data.csv")

df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

###  apply()

In [4]:


df2 = df.copy()

df2['text'] = df2['Salary'].apply(lambda x : "20%" if x >=50000 else "10%")

In [5]:
df2

   ID     Name  Age Department  Salary text
0   1    Alice   25         HR   55000  20%
1   2      Bob   32         IT   72000  20%
2   3  Charlie   28    Finance   48000  10%
3   4    David   45  Marketing   91000  20%
4   5      Eva   38         IT   65000  20%
5   6    Frank   29    Finance   50000  20%
6   7    Grace   41         HR   82000  20%
7   8   Hannah   26  Marketing   47000  10%
8   9      Ian   35         IT   75000  20%
9  10    Julia   30    Finance   60000  20%

### map()

In [6]:
df3 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pandas/raw_data.csv")
df3

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
df4 = df3.copy()

In [8]:
map_gender = {"Male" : "M", "Female" : "F","Unknown" : "U"}

df4['gender'] = df4['gender'].map(map_gender)

In [9]:
df4

    id          name   age country gender   income
0    1      John Doe  29.0     USA      M  55000.0
1    1      John Doe  29.0     USA      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN     USA      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0     USA      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0

### assign()

In [10]:
df4.assign(new_income = df4['income'] * 1.1)

    id          name   age country gender   income  new_income
0    1      John Doe  29.0     USA      M  55000.0     60500.0
1    1      John Doe  29.0     USA      M  55000.0     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0
3    3          Alex   NaN     USA      U  47000.0     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN
5    5        Li Wei  27.0   China      M  51000.0     56100.0
6    6           NaN  45.0   India      F  73000.0     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0     63800.0

### replace()

In [11]:
df4['country'] = df4['country'].replace("USA","United State")

In [12]:
df4

    id          name   age       country gender   income
0    1      John Doe  29.0  United State      M  55000.0
1    1      John Doe  29.0  United State      M  55000.0
2    2    Jane Smith   NaN        Canada      F  62000.0
3    3          Alex   NaN  United State      U  47000.0
4    4  Maria Garcia  34.0         Spain      F      NaN
5    5        Li Wei  27.0         China      M  51000.0
6    6           NaN  45.0         India      F  73000.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0
8    8    Rachel Lee  29.0  United State      F  62000.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0
10  10   Emily Davis  31.0  United State    NaN  58000.0

### rename()

In [13]:
# rename all columns name

df3.columns = ["Id","Name","Age","Country","Gender","Income"]

df3

# change one column

df3.rename(columns = {"Income" : "Salary"})

# chnage label

df3.rename(index = {1 : "One"})

     Id          Name   Age Country   Gender   Income
0     1      John Doe  29.0     USA     Male  55000.0
One   1      John Doe  29.0     USA     Male  55000.0
2     2    Jane Smith   NaN  Canada   Female  62000.0
3     3          Alex   NaN     USA  Unknown  47000.0
4     4  Maria Garcia  34.0   Spain   Female      NaN
5     5        Li Wei  27.0   China     Male  51000.0
6     6           NaN  45.0   India   Female  73000.0
7     7    Ahmed Khan  38.0     NaN     Male  68000.0
8     8    Rachel Lee  29.0     USA   Female  62000.0
9     9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10   10   Emily Davis  31.0     USA      NaN  58000.0

### sort()

In [17]:
# sort_values()
df3.sort_values("Income")

df3.sort_values(["Income","Age"])

df3.sort_values(["Income","Age"],ascending = False)

df3.sort_values(["Income","Age"],ascending = [False,True])

# sort_index()

    Id          Name   Age Country   Gender   Income
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
5    5        Li Wei  27.0   China     Male  51000.0
3    3          Alex   NaN     USA  Unknown  47000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN

In [16]:
# sort_index() , reset_index()
df3.sort_index()

    Id          Name   Age Country   Gender   Income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [18]:
df3.reset_index()

    index  Id          Name   Age Country   Gender   Income
0       0   1      John Doe  29.0     USA     Male  55000.0
1       1   1      John Doe  29.0     USA     Male  55000.0
2       2   2    Jane Smith   NaN  Canada   Female  62000.0
3       3   3          Alex   NaN     USA  Unknown  47000.0
4       4   4  Maria Garcia  34.0   Spain   Female      NaN
5       5   5        Li Wei  27.0   China     Male  51000.0
6       6   6           NaN  45.0   India   Female  73000.0
7       7   7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8   8    Rachel Lee  29.0     USA   Female  62000.0
9       9   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10  10   Emily Davis  31.0     USA      NaN  58000.0

In [20]:
#  rank()

sort_df = df3.sort_values("Income")

sort_df["rank"] = sort_df["Income"].rank()

sort_df

    Id          Name   Age Country   Gender   Income  rank
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   1.0
3    3          Alex   NaN     USA  Unknown  47000.0   2.0
5    5        Li Wei  27.0   China     Male  51000.0   3.0
1    1      John Doe  29.0     USA     Male  55000.0   4.5
0    1      John Doe  29.0     USA     Male  55000.0   4.5
10  10   Emily Davis  31.0     USA      NaN  58000.0   6.0
2    2    Jane Smith   NaN  Canada   Female  62000.0   7.5
8    8    Rachel Lee  29.0     USA   Female  62000.0   7.5
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   9.0
6    6           NaN  45.0   India   Female  73000.0  10.0
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN

In [24]:
# reorder columns

# df3.columns  => ['Id', 'Name', 'Age', 'Country', 'Gender', 'Income']

df3[['Id', 'Name', 'Age', 'Income' , 'Country', 'Gender']]

    Id          Name   Age   Income Country   Gender
0    1      John Doe  29.0  55000.0     USA     Male
1    1      John Doe  29.0  55000.0     USA     Male
2    2    Jane Smith   NaN  62000.0  Canada   Female
3    3          Alex   NaN  47000.0     USA  Unknown
4    4  Maria Garcia  34.0      NaN   Spain   Female
5    5        Li Wei  27.0  51000.0   China     Male
6    6           NaN  45.0  73000.0   India   Female
7    7    Ahmed Khan  38.0  68000.0     NaN     Male
8    8    Rachel Lee  29.0  62000.0     USA   Female
9    9   Carlos Ruiz   NaN  45000.0  Mexico     Male
10  10   Emily Davis  31.0  58000.0     USA      NaN

# write a csv/json file

In [28]:
# to_csv()
# to_json()

# make scv file with sorted data according to income

df5 = df.copy()

df5 = df5.drop_duplicates()

df5 = df5.fillna(0)

df5 = df5.sort_values("Salary")

df5 = df5.reset_index(drop = True)

df5.to_csv("Sorted_emp_data_base_on_salary.csv")