In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pandas/globalAirQuality.csv")

df

In [4]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [5]:
df.groupby("country")["aqi"].mean()

country
AE    105.530556
AR    105.950000
AU    103.461111
BR    104.319444
CA    104.544444
CH    105.722222
CN    102.893056
DE    104.422222
EG    106.052778
ES    105.488889
FI    105.108333
FR    105.763889
GB    103.044444
HK    103.488889
ID    104.316667
IN    104.265000
IR    102.150000
IT    105.033333
JP    104.997222
KE    104.747222
KR    105.119444
MX    105.697222
MY    105.005556
NG    106.616667
NZ    104.730556
PH    103.669444
PK    106.300000
PL    104.291667
QA    107.366667
RU    106.197222
SA    104.772222
SE    102.391667
SG    106.480556
TH    105.191667
TR    104.083333
US    104.482778
VN    101.536111
ZA    106.158333
Name: aqi, dtype: float64

In [6]:
df.groupby("country")["aqi"].min()

country
AE    43
AR    44
AU    36
BR    39
CA    42
CH    38
CN    27
DE    35
EG    42
ES    33
FI    35
FR    40
GB    16
HK    56
ID    48
IN    31
IR    35
IT    46
JP    33
KE    46
KR    43
MX    40
MY    32
NG    44
NZ    47
PH    32
PK    48
PL    31
QA    45
RU    48
SA    29
SE    42
SG    29
TH    27
TR    43
US    26
VN    39
ZA    35
Name: aqi, dtype: int64

In [7]:
df.groupby("country")["aqi"].max()

country
AE    189
AR    197
AU    193
BR    182
CA    188
CH    203
CN    183
DE    182
EG    190
ES    183
FI    231
FR    187
GB    214
HK    192
ID    198
IN    195
IR    177
IT    190
JP    204
KE    172
KR    183
MX    196
MY    194
NG    190
NZ    225
PH    206
PK    186
PL    197
QA    187
RU    197
SA    182
SE    196
SG    193
TH    194
TR    179
US    192
VN    179
ZA    190
Name: aqi, dtype: int64

In [8]:
df.groupby("country")["aqi"].agg(["mean","min","max"])

               mean  min  max
country
AE       105.530556   43  189
AR       105.950000   44  197
AU       103.461111   36  193
BR       104.319444   39  182
CA       104.544444   42  188
CH       105.722222   38  203
CN       102.893056   27  183
DE       104.422222   35  182
EG       106.052778   42  190
ES       105.488889   33  183
FI       105.108333   35  231
FR       105.763889   40  187
GB       103.044444   16  214
HK       103.488889   56  192
ID       104.316667   48  198
IN       104.265000   31  195
IR       102.150000   35  177
IT       105.033333   46  190
JP       104.997222   33  204
KE       104.747222   46  172
KR       105.119444   43  183
MX       105.697222   40  196
MY       105.005556   32  194
NG       106.616667   44  190
NZ       104.730556   47  225
PH       103.669444   32  206
PK       106.300000   48  186
PL       104.291667   31  197
QA       107.366667   45  187
RU       106.197222   48  197
SA       104.772222   29  182
SE       102.391667   42  196
SG       106.480556   29  193
TH       105.191667   27  194
TR       104.083333   43  179
US       104.482778   26  192
VN       101.536111   39  179
ZA       106.158333   35  190

In [9]:
df.groupby("country")["aqi"].agg(avg_aqi = "mean", minimun_aqi = "min",maximum_aqi = "max")

            avg_aqi  minimun_aqi  maximum_aqi
country
AE       105.530556           43          189
AR       105.950000           44          197
AU       103.461111           36          193
BR       104.319444           39          182
CA       104.544444           42          188
CH       105.722222           38          203
CN       102.893056           27          183
DE       104.422222           35          182
EG       106.052778           42          190
ES       105.488889           33          183
FI       105.108333           35          231
FR       105.763889           40          187
GB       103.044444           16          214
HK       103.488889           56          192
ID       104.316667           48          198
IN       104.265000           31          195
IR       102.150000           35          177
IT       105.033333           46          190
JP       104.997222           33          204
KE       104.747222           46          172
KR       105.119444           43          183
MX       105.697222           40          196
MY       105.005556           32          194
NG       106.616667           44          190
NZ       104.730556           47          225
PH       103.669444           32          206
PK       106.300000           48          186
PL       104.291667           31          197
QA       107.366667           45          187
RU       106.197222           48          197
SA       104.772222           29          182
SE       102.391667           42          196
SG       106.480556           29          193
TH       105.191667           27          194
TR       104.083333           43          179
US       104.482778           26          192
VN       101.536111           39          179
ZA       106.158333           35          190

In [11]:
df.groupby("country").agg(
    {
        "aqi" : "mean",
        "temperature" : "max",
        "humidity" : "min"
    }
)

                aqi  temperature  humidity
country
AE       105.530556       37.965    25.126
AR       105.950000       37.812    25.208
AU       103.461111       37.960    25.084
BR       104.319444       37.921    25.288
CA       104.544444       37.894    25.002
CH       105.722222       37.982    25.172
CN       102.893056       37.995    25.480
DE       104.422222       37.534    25.101
EG       106.052778       37.990    25.061
ES       105.488889       37.929    25.085
FI       105.108333       37.970    25.306
FR       105.763889       37.980    25.086
GB       103.044444       37.942    25.112
HK       103.488889       37.942    25.089
ID       104.316667       37.992    25.159
IN       104.265000       37.984    25.093
IR       102.150000       37.818    25.086
IT       105.033333       37.919    25.051
JP       104.997222       37.952    25.009
KE       104.747222       37.985    25.015
KR       105.119444       37.966    25.007
MX       105.697222       37.911    25.011
MY       105.005556       37.927    25.003
NG       106.616667       37.889    25.168
NZ       104.730556       37.990    25.132
PH       103.669444       37.898    25.192
PK       106.300000       37.905    25.271
PL       104.291667       37.947    25.167
QA       107.366667       37.859    25.106
RU       106.197222       37.950    25.026
SA       104.772222       37.810    25.281
SE       102.391667       37.977    25.386
SG       106.480556       37.699    25.121
TH       105.191667       37.768    25.030
TR       104.083333       37.816    25.096
US       104.482778       37.990    25.093
VN       101.536111       37.998    25.011
ZA       106.158333       37.895    25.006

In [13]:
df.groupby("country").agg(
      avg_aqi = ("aqi","mean"),
      max_tempperature = ("temperature","max"),
      min_humidity = ("humidity","min")
)

            avg_aqi  max_tempperature  min_humidity
country
AE       105.530556            37.965        25.126
AR       105.950000            37.812        25.208
AU       103.461111            37.960        25.084
BR       104.319444            37.921        25.288
CA       104.544444            37.894        25.002
CH       105.722222            37.982        25.172
CN       102.893056            37.995        25.480
DE       104.422222            37.534        25.101
EG       106.052778            37.990        25.061
ES       105.488889            37.929        25.085
FI       105.108333            37.970        25.306
FR       105.763889            37.980        25.086
GB       103.044444            37.942        25.112
HK       103.488889            37.942        25.089
ID       104.316667            37.992        25.159
IN       104.265000            37.984        25.093
IR       102.150000            37.818        25.086
IT       105.033333            37.919        25.051
JP       104.997222            37.952        25.009
KE       104.747222            37.985        25.015
KR       105.119444            37.966        25.007
MX       105.697222            37.911        25.011
MY       105.005556            37.927        25.003
NG       106.616667            37.889        25.168
NZ       104.730556            37.990        25.132
PH       103.669444            37.898        25.192
PK       106.300000            37.905        25.271
PL       104.291667            37.947        25.167
QA       107.366667            37.859        25.106
RU       106.197222            37.950        25.026
SA       104.772222            37.810        25.281
SE       102.391667            37.977        25.386
SG       106.480556            37.699        25.121
TH       105.191667            37.768        25.030
TR       104.083333            37.816        25.096
US       104.482778            37.990        25.093
VN       101.536111            37.998        25.011
ZA       106.158333            37.895        25.006