In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "country" : ["USA","USA","INDIA","INDIA"],
    "year" : [2020 , 2021 ,2020 ,2021],
    "sales" :  [100,120,90,110],
    "profit" : [20,25,18,22],
    "tax" : [10,20,40,30]
})

In [6]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   INDIA  2020     90      18   40
3   INDIA  2021    110      22   30

In [10]:
melted_df = df.melt(
    id_vars = ['country' , 'year'] ,
    value_vars = ['sales','profit','tax'],
    var_name = "matrix",
    value_name = "value"
)

In [11]:
melted_df

   country  year  matrix  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    INDIA  2020   sales     90
3    INDIA  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    INDIA  2020  profit     18
7    INDIA  2021  profit     22
8      USA  2020     tax     10
9      USA  2021     tax     20
10   INDIA  2020     tax     40
11   INDIA  2021     tax     30

In [13]:
pivot_df = melted_df.pivot(
    index = ['country','year'],
    columns = 'matrix',
    values = "value"
)

In [14]:
pivot_df

matrix        profit  sales  tax
country year
INDIA   2020      18     90   40
        2021      22    110   30
USA     2020      20    100   10
        2021      25    120   20