In [1]:
import pandas as pd

In [6]:
df_coustomers = pd.DataFrame({
    "coustomer_id" : [1,2,3,4],
    'name' : ["mit","kavy","kishan","dev"]
})

df_orders = pd.DataFrame({
    'order_id' : [101,102,103,104],
    'coustomer_id' : [2,1,3,5],
    'amount' : [250 , 120 ,300 ,180]
})

In [7]:
df_coustomers

   coustomer_id    name
0             1     mit
1             2    kavy
2             3  kishan
3             4     dev

In [8]:
df_orders

   order_id  coustomer_id  amount
0       101             2     250
1       102             1     120
2       103             3     300
3       104             5     180

In [9]:
# inner join
pd.merge(df_coustomers,df_orders,on='coustomer_id')

   coustomer_id    name  order_id  amount
0             1     mit       102     120
1             2    kavy       101     250
2             3  kishan       103     300

In [10]:
# left join
pd.merge(df_coustomers,df_orders,on="coustomer_id",how="left")

   coustomer_id    name  order_id  amount
0             1     mit     102.0   120.0
1             2    kavy     101.0   250.0
2             3  kishan     103.0   300.0
3             4     dev       NaN     NaN

In [11]:
# Right join
pd.merge(df_coustomers,df_orders,on="coustomer_id",how="right")

   coustomer_id    name  order_id  amount
0             2    kavy       101     250
1             1     mit       102     120
2             3  kishan       103     300
3             5     NaN       104     180

In [12]:
# outer join
pd.merge(df_coustomers,df_orders,on="coustomer_id",how="outer")

   coustomer_id    name  order_id  amount
0             1     mit     102.0   120.0
1             2    kavy     101.0   250.0
2             3  kishan     103.0   300.0
3             4     dev       NaN     NaN
4             5     NaN     104.0   180.0